[general]
; Set the day and night screen temperatures (Lower = Redder)
temp-day=1000
temp-night=1000

fade=1

adjustment-method=randr

location-provider=manual

dawn-time=6:00-7:45
dusk-time=18:35-20:15
